### ISSUE TITLE
editing mode and user mode

### ISSUE THREAD

**Issue by stefaniehoechtl** [asterics/AsTeRICS-Ergo#39] opened 2017-09-18 17:34 UTC
One participant recommends setting up an editing mode and an user mode, in order that the user cannot make accidential changes.

**Comment by deinhofer** [comment] 2017-09-18 17:36
This could be very important for cognitive disability or to prevent deleting buttons accidently by a user with motor impairment.

**Comment by klues** [comment] 2017-10-10 08:34
duplicate of https://github.com/asterics/AsTeRICS-Ergo/issues/87 -> closed

**Closed as completed by klues** 2017-10-10 08:34 UTC
Labels: Priority 3, result: user evaluation
