### ISSUE TITLE
FS20 Patch and FS20 testing not properly working on Win8

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS-Ergo#21] opened 2017-09-12 14:02 UTC
**Problem**
I have done several tests on Win8, but the problem may also be valid for Win 8.1. On Win10 the patching of the FS20 worked.

Test run 1
1) AsTeRICS Ergo started (FS20 plugged in, LED dark)
2) FS20 Test executed, Result: OK (**false**,  LED actually dark)
3) "Add device" selected: FS20-Test-Result: Missing (correct) 
4) "Fix problem" clicked, FS20 plugged off/on --> LED dark
5) FS20 Test: hangs, does not end
6) When trying to open the ARE on the system tray, it crashes (disappears from System-Tray)

Test run 2
identical

Test run 3
1) AsTeRICS Ergo executed as ADMINISTRATOR (FS20 is plugged in, LED dark)
2) FS20 Test executed, Result: OK (**false**,  LED actually dark)
3) "Add device" selected: FS20-Test-Result: Missing (correct) 
4) "Fix problem" clicked, FS20 plugged off/on --> LED **bright**
Unfortunately the fix is not permanent, the "PowerManagement" flag in the registry is still enabled and the LED is only on if the ARE is running. When you stop the ARE, the LED is off. If you start the ARE as administrator again, the LED is on after pugging off/on the FS20 module.

Conclusion:
1.2) Happened always, but probably only the first run of the test?
1.4) I was not asked for an administrator password, which the User Access Control of Windows should normally do. This could be the reason why the patching did not work (due to permission denied)
1.5) Is there a timeout missing?
1.6) Was probably caused by the hanging FS20 test?

Other questions
Why does the patch not actually change the registry also as administrator? Maybe the registry key under windows is different?

**Resolved if**
Patching the FS20 device on Win 8, maybe also Win8.1 is successful and the LED goes on and the FS20 can be used.

**Comment by klues** [comment] 2017-09-28 13:38
Did some more tests on a windows 8.1 Tablet.
Strange behaviour:
* starting start-debug-webservice.bat from asterics-repo -> patching FS20 in assistant works, registry is changed! (non-administrator). strange: i do not get any UAC-control message, changing the registry just happens...
* Starting start-debug-webservice.bat from installed asterics-ergo version in appdata --> patching FS20 in assistant does not work, registry is not changed! I have no clue why

The bug that the assistant says that FS20 is installed, although it is not is known, but I also do not know why it happens. I've already debuged it and sometimes also the call in the Java plugin returns a success although the FS20-sender is not connected.
Maybe I'll fix it by double-checking.

**Comment by klues** [comment] 2017-09-28 14:00
narrowed down the problem, did 2 tests:
* run start-debug-webservice.bat from C:\Users\<User>\AppData\Local\AsTeRICS Ergo\app --> Registry patch did not work
* copy "app"-folder to desktop and run start-debug-webservice.bat --> patch works!

so it is somehow related to the fact, that asterics-ergo is installed to the "AppData"-Folder. @deinhofer why this is the case? why it is not installed to C:\Program Files like other programs? Did you run your tests with AsTeRICS-Ergo installed to AppData or to Program Files?

**Comment by klues** [comment] 2017-09-28 14:59
Also tested on Win 10:
* normal start via .exe after install -> FS20 Patch does **not** work
* starting via start-debug-webservice.bat in AppData -> FS20 Patch does **not** work
* copy everything to desktop and start via start-debug-webservice.bat -> FS20 Patch does **not** work
* start from git-repo-folder (on usb-disk) via start-debug-webservice.bat -> FS20 Patch **works**!
very strange...

**Comment by klues** [comment] 2017-09-28 15:05
so the question are:
* how it can be that the patch does not work in AppData, but on Desktop on Win8?
* why does the patch does not work at all from the installed version but from the git-version on Win10?

**Comment by klues** [comment] 2017-09-29 09:09
it defenitely has to do something with the path asterics ergo is installed. some more tests:
* start with .bat in Desktop/app -> works
* start with .bat in "Desktop/app 2" -> does not work
* start with .exe in "Desktop/AsTeRICS Ergo" -> does not work
* start with .exe in "Desktop/AsTeRICSErgo" -> works

so it works if the path does not have a space.
I'll investigate why..

**Comment by klues** [comment] 2017-09-29 11:04
fixed patch-script with: https://github.com/asterics/AsTeRICS/pull/141/commits/c015ab85ca24786bce0d4b44bb47bc6417e24aa6
fixed problem that fs20 is shown as "connected" while it is not with https://github.com/asterics/AsTeRICS-Ergo/pull/81

released with https://github.com/asterics/AsTeRICS-Ergo/releases/tag/v3.2.3 and tested with Win10 and Win8 -> Patching Worked!
Java once crashed after patching, I do not know why. Maybe someone should test it again and then we could close this issue :)

**Comment by deinhofer** [comment] 2017-10-02 12:35
great! Will test it again.
Does it also work without Administrator privileges on Win8 now?

**Comment by klues** [comment] 2017-10-02 12:44
on my test on out win8 tablet it worked without administrator privileges. however i did not get a UAC-dialog, it just worked -> strange.

**Comment by deinhofer** [comment] 2017-10-02 16:18
@deinhofer: The rare crashes of the ARE (see point 1.6) are still unclear. --> Check patch implementaiton regarding multi-threading and model executor thread.
The other points should work already --> Test it

**Comment by deinhofer** [comment] 2017-10-11 19:34
changed patch implementation to use temp files which are automatically deleted on program exit.

regarding multi-threading we should change the SendCallable so that it is guaranteed that all the operations (open, read, write, close) are done within the same thread. Maybe we should open/close the device after each command. A good solution could also be to use a dedicated FS20 device thread which waits for data on a queue (https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/BlockingQueue.html) and automatically opens/closes the device on demand.

**Comment by klues** [comment] 2017-10-12 08:08
ok, thanks for improving the patch implementation.
I will look on the thing with the SendCallable, when I have time -> I'll add it to my TODO-list

**Comment by klues** [comment] 2017-10-19 12:44
@deinhofer: regarding multi-threading:
what is the goal of your suggested changes? to prevent that several threads send something to FS20 at the same time, correct?
then why not just make this method:
https://github.com/asterics/AsTeRICS/blob/e21e2b553cab77121ee0c4e1e36338d2ee78bf74/ARE/components/actuator.fs20sender/src/main/java/eu/asterics/component/actuator/fS20Sender/PCSDevice.java#L107
synchronized?

**Comment by deinhofer** [comment] 2017-10-19 15:39
no, it's ´not only about preventing a concurrent access, it is also about ensuring that the native access is always done by the same thread, because some native libs crash if the device is used by different threads even when synchronized

**Comment by klues** [comment] 2017-10-19 15:42
really? also if the old threads do not exist anymore?
ok, then I'll see what I can achieve...

**Comment by deinhofer** [comment] 2017-10-19 16:05
at least this was the case for the former hid library.
What if you simply use the same ExecutorService instance for executing open, write, read and close?

**Comment by klues** [comment] 2017-10-20 11:26
opened new issue https://github.com/asterics/AsTeRICS/issues/182 so that this will not be forgotten.

**Comment by klues** [comment] 2017-10-30 16:40
just tested on Win10/Edge:
* checking if FS20 connected does not finish
* after patching registry, ARE crashed without error message.

just this in the logs:
Okt 30, 2017 5:33:52 PM eu.asterics.component.actuator.fS20Sender.FS20SenderInstance$3 receiveData
SCHWERWIEGEND: java.lang.NullPointerException

but this happened actually before patching:
Okt 30, 2017 5:34:25 PM eu.asterics.component.actuator.fS20Sender.FS20SenderInstance$3 receiveData
INFORMATION: successfully patched registry for FS20.

**Comment by klues** [comment] 2017-10-31 09:54
Steps to reproduce ARE crash:
* uninstall FS20 device
* connect FS20 device to computer
* wait until red light is dark
* open AsTeRICS-Ergo (v.3.3.0), go to FS20 installation wizard
* click on "solve problem" ("problem beheben") -> registry is patched
* click on "Test" - Button several times -> test fails because FS20 was not re-connected and red light is still dark
* disconnect FS20 USB plug
* connect it again and very shortly after USB re-connect press on "Test" again in the webapp
* ARE - icon disappears from tray -> crashed

tested in Edge, Firefox and Chrome, so this is Browser independent.

**Comment by klues** [comment] 2017-10-31 09:57
also reproduced this in debug-mode now, there is no exception but:
`Java returned: -1073740940`

**Comment by klues** [comment] 2017-10-31 11:42
second way to reproduce:
* uninstall FS20 device
* connect FS20 device to computer
* wait until red light is dark
* open AsTeRICS-Ergo (v.3.3.0), go to FS20 installation wizard
* do not click on "solve" problem, but directly go to "Test"
* While test is running, disconnect FS20 USB
* ARE crashes

**Comment by klues** [comment] 2017-11-02 09:04
ARE crashes should be fixed with https://github.com/asterics/AsTeRICS/issues/182
so I think we can close this issue.

**Closed as completed by klues** 2017-11-02 09:04 UTC
Labels: Priority 1, fixed?
